modLoader="javafml"
loaderVersion="[36,)"
license="All Rights Reserved"

[[mods]]
modId="evky"
version="1.1.14B"
displayName="EVKY"
credits="MinerChickenDine, Teengamer120"
displayURL="https://github.com/EvKy/EvKy1"
logoFile="logo.png"
authors="MinerChickenDine, Teengamer120"

[[dependencies.evky]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




